### ISSUE TITLE
Not all resources are removed upon appsub removal

### ISSUE THREAD

**Issue by ahadas** [open-cluster-management/multicloud-operators-subscription#179]
When adding an appsub, all its resources are given an annotation that specifies their relation  with that appsub, so they will also be removed when removing the appsub.

This is fine in the general case but might fail when the application itself spawns other resources like pods without propagating that annotation to the spawned resources.

One may argue that when removing the appsub the appsub should only be responsible to remove its direct resources and the application is responsible to remove the spawned resources; or that the application is responsible to propagate the aforementioned annotation into its spawned resources. But this is hard to enforce.

A possible solution for this may be to remove all entities within the appsub's namespace, no matter if they have that annotation or not. Need to be careful not to remove things that will be part of the admin-namespace (for multi-namespace appsubs) though.

**Comment by jnpacker** [comment]
I can't see us removing resources we were not directly responsible for. Like if we deployed an operator, we would expect the operator to own cleanup of the operand when we attempted to remove it.

We open to offering the other direction, where we provide a switch to leave all artifacts created by the subscription behind. Plz reach out if you see a benefit from that one.
