### ISSUE TITLE
Appsub requires an ordered list of resources

### ISSUE THREAD

**Issue by ahadas** [open-cluster-management/multicloud-operators-subscription#180]
The current mechanism assumes entities to be defined are given in a logical order, i.e., a resource is identified after the resources it depends on were identified. This doesn't hold when the application is composed of several (yaml) files.

For instance, let's say that a CR is defined in one file and its CRD is defined in another file. It may be the case that OCM will try to apply the CR from the first file before applying the CRD from the other file.

This can be solved by adding a random mechanism by which OCM tries to apply resources that spread across different files.

**Comment by rokej** [comment]
The subscription applies CRDs and namespaces first. Then it applies RBAC related resource if there is any. You can also use kustomize to get a correct ordered list of resources.

**Comment by ahadas** [comment]
@rokej right but this assumes the application uses kuztomize which may not necessarily be the case. take KubeVirt for instance [1]: they provide two yamls, for the operator and the CR without using kustomize.

[1] https://github.com/kubevirt/kubevirt/releases

**Comment by ahadas** [comment]
> The subscription applies CRDs and namespaces first. Then it applies RBAC related resource if there is any. 

But we see it depends on the filenames, right? if the file 'a.yaml' will include the CR and file 'b.yaml' include the CRD and namespace - seems the appsub always fails

> You can also use kustomize to get a correct ordered list of resources.
@rokej right but it's not "me" but "others" :) and in that case we, in my opinion, should not assume they use kuztomize. take KubeVirt for instance [1]: they provide two yamls, for the operator and the CR without using kustomize.

[1] https://github.com/kubevirt/kubevirt/releases

**Comment by rokej** [comment]
The order does not depend on the file names. The subscription actually looks at the kind in the YAML to sort them into different priorities so that CRDs get applied first. The  problem you encountered was not because CR was applied before CRD. It was due to some other problem within subscription that has to do with GVK validation of the CR. That problem should be fixed.

**Comment by ahadas** [comment]
I see, but specifically the kubevirt configuration failed consistently for us with the OCM build from Apr 24 until we renamed the files...

**Comment by rokej** [comment]
Oh.. it still failed with `1.0.0-SNAPSHOT-2020-04-24-01-14-43` or newer build and renaming the file fixed the problem?

**Comment by ahadas** [comment]
Yes, it seems so.
The CRD wasn't applied so we renamed the files [1, 2], with the renamed files we got it and then we renamed the CR as suggested in #166 [3] so it will also be applied.

[1] https://github.com/danielerez/ocm-gitops-policy/commit/b0f0b56d901619dd8a9d845bbd6dbae22fd0d49a
[2] https://github.com/danielerez/ocm-gitops-policy/commit/88cb40c7b0c7d868185e03120466ac29bf6eeea7
[3] https://github.com/danielerez/ocm-gitops-policy/commit/e616ecfedd6aa5d3986b80ce7e18dffddc60ad37

**Comment by rokej** [comment]
The subscription does not work with file names so I doubt that changing the file names fixed the problem. If you kept the subscription (not delete and recreate), that explains that when you made those changes in your git repo, it changed the commit of the repo which triggers the subscription to apply the resources again if there is any change. That could have fixed the problem.

**Comment by ahadas** [comment]
Ah ok, yeah, we didn't delete and recreated the subscription so that's possible.

**Comment by ahadas** [comment]
@rokej I've tried to reproduce it again and I get the following messages in the log every minute:
```
I0428 12:16:55.648273       1 synchronizer.go:385] Obj /openshift-performance-addon exists and owned by others, backoff
I0428 12:17:11.165310       1 gitrepo.go:116] Cloning https://github.com/danielerez/ocm-gitops-policy.git into /tmp/ec/ec-channel/master
W0428 12:17:11.951306       1 gitrepo.go:76] Not a Kubernetes resource
I0428 12:17:11.951530       1 gitrepo.go:369] kubevirt.io/v1alpha3/KubeVirt
W0428 12:17:11.951729       1 gitrepo.go:76] Not a Kubernetes resource
I0428 12:17:11.954407       1 gitrepo.go:386] Multi resource
I0428 12:17:11.954421       1 gitrepo.go:340] otherFiles size 
W0428 12:17:11.954436       1 helmrepo.go:331] subsciption.spec.name is missing for subscription: kubevirt/cnv-appsub
W0428 12:17:11.954565       1 gitrepo.go:76] Not a Kubernetes resource
I0428 12:17:11.954874       1 subscriber_item.go:319] Skipping resource
E0428 12:17:11.954884       1 subscriber_item.go:302] Failed to apply a resource, error: Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supported
E0428 12:17:11.954893       1 subscriber_item.go:169] Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supportedUnable to subscribe resource
E0428 12:17:11.954898       1 subscriber_item.go:104] Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supportedSubscription error.
I0428 12:17:13.982972       1 gitrepo.go:116] Cloning https://github.com/danielerez/ocm-gitops-policy.git into /tmp/ec/ec-channel/master
I0428 12:17:14.780893       1 gitrepo.go:340] otherFiles size 
W0428 12:17:14.780945       1 helmrepo.go:331] subsciption.spec.name is missing for subscription: openshift-performance-addon/cnf-appsub
I0428 12:17:14.781056       1 subscriber_item.go:213] Applying kustomization /tmp/ec/ec-channel/master/cnf/performance/
I0428 12:17:14.788430       1 subscriber_item.go:319] Skipping resource
E0428 12:17:14.788503       1 subscriber_item.go:262] Failed to apply a resource, error: Resource performance.openshift.io/v1alpha1, Kind=PerformanceProfile is not supported
E0428 12:17:14.788538       1 subscriber_item.go:178] Resource performance.openshift.io/v1alpha1, Kind=PerformanceProfile is not supportedUnable to subscribe resource
E0428 12:17:14.788566       1 subscriber_item.go:104] Resource performance.openshift.io/v1alpha1, Kind=PerformanceProfile is not supportedSubscription error.
I0428 12:17:56.804906       1 synchronizer.go:385] Obj /openshift-performance-addon exists and owned by others, backoff
```

There are two appsubs - cnv-appsub and cnf-appsub, let's ignore the latter and look only at cnv-appsub that brings the KubeVirt resources.

IIUC, the repository is cloned and then it fails on the KubeVirt CR (due to `Not a Kubernetes resource`). I've added several commits to the repo and changes the resources required for the operator, but I don't see any change in the log.

Only when we rename the files, there seems to be an attempt to apply the CRD:
```
E0428 12:25:14.402006       1 synchronizer.go:354] Failed to apply resource with error: CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha3", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc017bcc4b0), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
E0428 12:25:14.402086       1 synchronizer.go:461] Failed to apply kind template&{map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[annotations:map[apps.open-cluster-management.io/hosting-deployable:ec/ec-channel-CustomResourceDefinition-kubevirts.kubevirt.io apps.open-cluster-management.io/hosting-subscription:kubevirt/cnv-appsub apps.open-cluster-management.io/sync-source:subgbk8s-kubevirt/cnv-appsub] labels:map[operator.kubevirt.io:] name:kubevirts.kubevirt.io] spec:map[additionalPrinterColumns:[map[JSONPath:.metadata.creationTimestamp name:Age type:date] map[JSONPath:.status.phase name:Phase type:string]] group:kubevirt.io names:map[categories:[all] kind:KubeVirt plural:kubevirts shortNames:[kv kvs] singular:kubevirt] scope:Namespaced version:v1alpha3 versions:[map[name:v1alpha3 schema:map[openAPIV3Schema:map[properties:map[spec:map[properties:map[cronSpec:map[type:string] image:map[type:string] replicas:map[type:integer]] type:object]] type:object]] served:true storage:true]]]]}with error:CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha3", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc017bcc4b0), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
```

Are you sure the sorting you've mentioned is done on all entities within all resources that are retrieved from the repo and not per-file?

**Comment by rokej** [comment]
@ahadas I get the same log messages as you do.

```
I0428 10:37:39.475322   38490 gitrepo.go:116] Cloning https://github.com/rokej/rokejtest.git into /var/folders/g5/j5zc0ll57cvchdbn25ybf1gh0000gn/T/default/github-crd/master
W0428 10:37:39.848744   38490 gitrepo.go:76] Not a Kubernetes resource
I0428 10:37:39.848861   38490 gitrepo.go:369] kubevirt.io/v1alpha3/KubeVirt
W0428 10:37:39.848936   38490 gitrepo.go:76] Not a Kubernetes resource
I0428 10:37:39.849272   38490 gitrepo.go:369] apiextensions.k8s.io/v1beta1/CustomResourceDefinition
I0428 10:37:39.849281   38490 gitrepo.go:340] otherFiles size 
W0428 10:37:39.849288   38490 helmrepo.go:331] subsciption.spec.name is missing for subscription: default/github-crd
W0428 10:37:39.849411   38490 gitrepo.go:76] Not a Kubernetes resource
W0428 10:37:39.850149   38490 gitrepo.go:76] Not a Kubernetes resource
I0428 10:37:39.850327   38490 subscriber_item.go:319] Skipping resource
E0428 10:37:39.850337   38490 subscriber_item.go:302] Failed to apply a resource, error: Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supported
E0428 10:37:39.850344   38490 subscriber_item.go:169] Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supportedUnable to subscribe resource
E0428 10:37:39.850348   38490 subscriber_item.go:104] Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supportedSubscription error.
E0428 10:37:56.038315   38490 synchronizer.go:354] Failed to apply resource with error: CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha3", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc043048690), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
E0428 10:37:56.038359   38490 synchronizer.go:461] Failed to apply kind template&{map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[annotations:map[apps.open-cluster-management.io/hosting-deployable:default/github-crd-CustomResourceDefinition-kubevirts.kubevirt.io apps.open-cluster-management.io/hosting-subscription:default/github-crd apps.open-cluster-management.io/sync-source:subgbk8s-default/github-crd] labels:map[operator.kubevirt.io:] name:kubevirts.kubevirt.io] spec:map[additionalPrinterColumns:[map[JSONPath:.metadata.creationTimestamp name:Age type:date] map[JSONPath:.status.phase name:Phase type:string]] group:kubevirt.io names:map[categories:[all] kind:KubeVirt plural:kubevirts shortNames:[kv kvs] singular:kubevirt] scope:Namespaced version:v1alpha3 versions:[map[name:v1alpha3 schema:map[openAPIV3Schema:map[properties:map[spec:map[properties:map[cronSpec:map[type:string] image:map[type:string] replicas:map[type:integer]] type:object]] type:object]] served:true storage:true]]]]}with error:CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha3", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc043048690), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
```

What I said about the ordering is still true. 

```
E0428 10:37:39.850337   38490 subscriber_item.go:302] Failed to apply a resource, error: Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supported
E0428 10:37:39.850344   38490 subscriber_item.go:169] Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supportedUnable to subscribe resource
E0428 10:37:39.850348   38490 subscriber_item.go:104] Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supportedSubscription error.
E0428 10:37:56.038315   38490 synchronizer.go:354] Failed to apply resource with error: CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io" is invalid: spec.versions: Invalid value: 
```

I think you are concerned because `Failed to apply a resource, error: Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supported` message comes before `Failed to apply resource with error: CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io` is invalid: spec.versions: Invalid value: `. `Failed to apply a resource, error: Resource kubevirt.io/v1alpha3, Kind=KubeVirt is not supported` message comes from GVK validation and saying there is no CRD in the cluster for this resource.  The second message `Failed to apply resource with error: CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io` comes from trying to apply the CRD. So yes, the subscription controller `applies` CRDs before anything else.

In fact, the validation of CRDs occurred before other things but you don't see it in the log because they passed.

**Comment by rokej** [comment]
Now, we should focus on why applying CRD fails. It is still the same problem as https://github.com/open-cluster-management/multicloud-operators-subscription/issues/170. I thought that was fixed but still the same.

As @ianzhang366  suggested, change https://github.com/danielerez/ocm-gitops-policy/blob/e1f6adb3ac4ff5387a7fa3ccdcfe7dd7185f2c95/kubevirt/kubevirt-operator.yaml#L9 to `apiextensions.k8s.io/v1` for now to get around the problem.

**Comment by rokej** [comment]
@ahadas Can I close this issue?

**Comment by ahadas** [comment]
I'd prefer to keep this open until we see the kubevirt resources being applied successfully

**Comment by rokej** [comment]
@ahadas Can I close this?

**Comment by ahadas** [comment]
@rokej from my side - yes, if you merged a fix and checked that it works now you can close it. if one finds that it's not resolve, it can be reopen.
