### ISSUE TITLE
Support for multi-namespace application

### ISSUE THREAD

**Issue by ahadas** [open-cluster-management/multicloud-operators-subscription#184]
Issues we expect [the ongoing effort to enable defining an appsub that is able to apply resources on various namespaces](https://github.com/open-cluster-management/backlog/blob/master/architecture/Application_Lifecycle/2020-GA_multi-namespace-subscriptions.md) to solve:

1. Having one appsub that retrieves other appsubs from a git repository - this way OCM can define one appsub for essential configurations and the other appsubs would be configured within the git repo (e.g., for CNV, CNF).

2. Support appsubs that apply resources on various namespaces - OCM currently seems to support  appsubs that define resources in a namespace that is associated with it, the default namespace and non-namespaced resources. But we need to support CNF's performance-addon-operator that applies non-namespaced resources as well as resources in the operator's namespace (openshift-performance-addon) and in the openshift-marketplace namespace.

@jnpacker fyi

**Comment by jnpacker** [comment]
Agreed, we are pushing hard to enable this capability, but we are having trouble doing it securely. We believe we have a path now, that we should confirm this week, and if so, we will be able to address multi namespace

**Comment by jnpacker** [comment]
@rokej can you duplicate this to your current issue if you have one, otherwise please update status here going forward.

**Comment by rokej** [comment]
This was implemented. Tracking with https://github.com/open-cluster-management/backlog/issues/1295.
